# Generated by Django 3.2 on 2021-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210523_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='main',
            field=models.BooleanField(default=1, verbose_name='Основной'),
            preserve_default=False,
        ),
    ]
